- hosts: web
  become: yes
  tasks:
   - name: Install Java 1.8
     apt:     ## apt-get install openjdk-8-jdk -y
      name: openjdk-8-jdk
      state: present

   - name: add group "maven"
     group:  ## groupadd maven
       name: maven

   - name: add user "maven"
     user:  ## useradd maven -G maven
      name: maven
      group: maven
      createhome: no

   - name: Download Maven
     get_url:  ### wget url -O /tmp/tomca.tgz
       url: https://dlcdn.apache.org/maven/maven-3/3.8.3/binaries/apache-maven-3.8.3-bin.tar.gz
       dest: /tmp/apache-maven-3.8.3-bin.tar.gz

   - name: Extract archive
     unarchive:  ## tar -xzf tarfile ## by default source is always controller
        src: /tmp/apache-maven-3.8.3-bin.tar.gz
        dest: /opt
        remote_src: yes

   